/** Canonical 15 nav permission keys — aligned with RBAC_BACKEND_15_PERMISSIONS.md */

export const NAV_PERMS = {
  OPPORTUNITIES_ALL: 'nav.opportunities.all',
  PROPOSALS_NEW_DIRECT: 'nav.proposals.new_direct',
  MM_MY_PROPOSALS: 'nav.matchmaking.my_proposals',
  MM_NEW: 'nav.matchmaking.new_proposal',
  MM_REVIEW_QUEUE: 'nav.matchmaking.review_queue',
  MM_FORWARDED: 'nav.matchmaking.forwarded',
  MM_BOARD: 'nav.matchmaking.matching_board',
  MM_MATCHES: 'nav.matchmaking.all_matches',
  COMPLAINTS_ALL: 'nav.complaints.all',
  USERS: 'nav.users.manage',
  SECTORS: 'nav.sectors.manage',
  PERMISSIONS: 'nav.permissions.manage',
  SL_REASSIGN: 'nav.sector_lead.reassign',
  COMPLIANCE: 'nav.compliance.audit',
  CHANGE_PASSWORD: 'nav.account.change_password',
}

/** Route guards: any listed permission grants access (legacy read aliases handled in rbac.js). */
export const ROUTE_ACCESS = {
  partyADashboard: [NAV_PERMS.MM_MY_PROPOSALS, NAV_PERMS.OPPORTUNITIES_ALL],
  partyAProfile: [NAV_PERMS.MM_MY_PROPOSALS],
  partyBDashboard: [NAV_PERMS.COMPLAINTS_ALL],
  partyBProfile: [NAV_PERMS.COMPLAINTS_ALL],
  newDirectProposal: [NAV_PERMS.PROPOSALS_NEW_DIRECT],
  mmMyProposals: [NAV_PERMS.MM_MY_PROPOSALS],
  mmNew: [NAV_PERMS.MM_NEW, 'matchmaking.create'],
  mmReviewQueue: [NAV_PERMS.MM_REVIEW_QUEUE],
  mmForwarded: [NAV_PERMS.MM_FORWARDED],
  mmBoard: [NAV_PERMS.MM_BOARD],
  mmMatches: [NAV_PERMS.MM_MATCHES],
  mmAllProposals: [NAV_PERMS.MM_BOARD, NAV_PERMS.MM_REVIEW_QUEUE],
  sectorLeadDashboard: [NAV_PERMS.OPPORTUNITIES_ALL, NAV_PERMS.MM_FORWARDED],
  superAdminDashboard: [NAV_PERMS.OPPORTUNITIES_ALL],
  regionalFocal: [NAV_PERMS.MM_REVIEW_QUEUE, NAV_PERMS.MM_FORWARDED],
  complaints: [NAV_PERMS.COMPLAINTS_ALL, 'complaints.review'],
  complaintsNew: ['complaints.create', NAV_PERMS.COMPLAINTS_ALL],
  partyAProfiles: [NAV_PERMS.USERS],
  partyBProfiles: [NAV_PERMS.USERS],
  users: ['nav.users.manage', 'admin.users', 'users.manage'],
  permissions: ['nav.permissions.manage', 'admin.rbac'],
  sectors: ['nav.sectors.manage', 'admin.sectors'],
  slReassign: ['nav.sector_lead.reassign', 'admin.sl_reassign'],
  slHandoff: ['nav.sector_lead.reassign', 'admin.sl_reassign'],
  compliance: ['nav.compliance.audit', 'admin.compliance'],
  adminSettings: [
    'nav.users.manage',
    'admin.users',
    'users.manage',
    'nav.sectors.manage',
    'admin.sectors',
    'nav.permissions.manage',
    'admin.rbac',
    'nav.sector_lead.reassign',
    'admin.sl_reassign',
    'nav.compliance.audit',
    'admin.compliance',
  ],
  proposalDetail: [
    NAV_PERMS.OPPORTUNITIES_ALL,
    NAV_PERMS.MM_MY_PROPOSALS,
    NAV_PERMS.MM_REVIEW_QUEUE,
    NAV_PERMS.MM_FORWARDED,
    NAV_PERMS.MM_BOARD,
    NAV_PERMS.MM_MATCHES,
    NAV_PERMS.PROPOSALS_NEW_DIRECT,
    'proposals.view',
  ],
  mmProposalDetail: [
    NAV_PERMS.MM_MY_PROPOSALS,
    NAV_PERMS.MM_REVIEW_QUEUE,
    NAV_PERMS.MM_FORWARDED,
    NAV_PERMS.MM_BOARD,
    NAV_PERMS.MM_NEW,
  ],
}
